### ISSUE TITLE
Command not found error

### ISSUE THREAD

**Issue by Nimon77** [necatiarslan/aws-s3#1]
Hi !

I'm currently on Fedora 37 and i just dowloaded your extension but I can't use it, I got command not found error on every buttons and nothing showing up in the bucket list :cry: my conf seem good because `aws s3 ls` show my buckets :

![image](https://user-images.githubusercontent.com/11821952/209556110-36a79257-fbc2-4921-9228-938a0c2b007c.png)

![image](https://user-images.githubusercontent.com/11821952/209556048-00e958ae-4f3f-42a0-b9e4-5f89723303a8.png)

**Comment by necatiarslan** [comment]
I am developing and testing it on macos. There is no os specific developments in it, so it should work on any os. 

- Can you look into vscode logs and give more detail ? In the output panel bottom.

- Can you see the commands and views when you go to aws s3 extension in the extensions panel ?


I will install linux and test as soon as possible.

**Comment by Nimon77** [comment]
I have this in the console :
![image](https://user-images.githubusercontent.com/11821952/209566433-348833c7-079d-4d67-9d68-a9aa8ac70a6b.png)

**Comment by necatiarslan** [comment]
There must be an issue with your installation.
The typical installation folder is like this

- /home/nimon/.vscode/extensions/necatiarslan.aws-s3-vscode-extension-1.0.9/

You should have a ui.js file in this folder

- /home/nimon/.vscode/extensions/necatiarslan.aws-s3-vscode-extension-1.0.9/out/common/ui.js

Can you check both of these folders?

**Comment by Nimon77** [comment]
The file is present :/

![image](https://user-images.githubusercontent.com/11821952/209652493-187684fa-d6c2-4249-b914-b59b48b9b917.png)

I found a fix, I make a PR right now ;)

**Comment by necatiarslan** [comment]
Thanks for the fix. I have released 1.0.10 now. I hope this will fix the issue

**Comment by Nimon77** [comment]
The issue seem to be fixed now !

Unfortunately I can't use it for my Scalway S3 buckets because the endpoint_url is not get from my `~/.aws/config` but for AWS it work fine ;)
