### ISSUE TITLE
Copy S3 URI feature request

### ISSUE THREAD

**Issue by ilyavs** [necatiarslan/aws-s3#10]
Hello,
The extension is very useful and convenient to use. I would love to have the option to copy the S3 URI of directories and files similarly to the options in the web API for S3.
Thanks!

**Comment by necatiarslan** [comment]
You can copy the S3 URIs of selected files and folders like below.

![image](https://github.com/necatiarslan/aws-s3/assets/1336688/97e8c5c4-6363-4835-b0a3-1c3d83ee7158)
