### ISSUE TITLE
not able to create the folder 

### ISSUE THREAD

**Issue by feeroz21** [necatiarslan/aws-s3#11]
Whenever I attempt to create a folder, it ends up creating a file instead.

**Comment by feeroz21** [comment]
While uploading the files its gives the error

api.UploadS3File Error !!! File=/D:/Floor-heat/Image-5.jpg | Error | ENOENT: no such file or directory, open **'C:\D:\**test\Image-5.jpg'

Its seems by defaults path C:\ , even I try to upload the file from D folder
If I try to upload the file from C directory it take one more level & gives error:
| Error | ENOENT: no such file or directory, open **'C:\C:\** <file path>

**Comment by necatiarslan** [comment]
pls try again with the new version 1.3
