### ISSUE TITLE
Local S3 improvement

### ISSUE THREAD

**Issue by Ferabeo** [necatiarslan/aws-s3#12]
Hello,

First, thanks for this vscode extension !
I'm using this extension for local usage (custom enpoint parameter is very useful).

I have multiples profiles with differents credentials. Profiles cannot list all buckets for security purposes.
When I try to add a bucket by name, it's trying to list all (see error below).

Would it be possible to try to connect directly to the bucket before (or instead) of trying to list them all ?

```
api.GetBucketList Error !!!
AccessDenied
Access Denied
AccessDenied: Access Denied
```

**Comment by necatiarslan** [comment]
I have added this to version 1.3, I will release it today

**Comment by necatiarslan** [comment]
I have added extended aws credentials support with the new version v1.7.1
Pls install and retry and let me know if it worked or not
