### ISSUE TITLE
Problem connecting to an in-house CEPH S3 endpoint

### ISSUE THREAD

**Issue by ymoisan** [necatiarslan/aws-s3#13]
Hi.  Thanx for your VSCode extension !

I'm having issues connecting to a CEPH S3 storage that I can otherwise access perfectly well in a Jupyter notebook with `s3fs` : 

```
s3 = s3fs.S3FileSystem(
   key=access_key,
   secret=secret_access_key,
   client_kwargs={
       'endpoint_url': endpoint_url
   }
)
```

Now, I've put a credentials file in HOME/.aws : 
```
[default]
aws_access_key_id=my_access_key
aws_secret_access_key=my_secret_access_key
endpoint_url = http://my_url
```
thinking it might automagically work with your extension but instead I get a warning from your extension : "Your Aws Access method is not credentials file".

Any hints ?

Thank you !

**Comment by ymoisan** [comment]
Thank you for instructions.  I added this to my `settings.json` file :

```
"terminal.integrated.env.windows": {
        "aws_access_key_id": "MY_KEY_IN_QUOTES",
        "aws_secret_access_key": "MY_SECRET_KEY_IN_QUOTES"        
    }
```
Are those env vars accessible to your extension ?

I tried the following in the end point URL text zone : 
- http://my_url:my_port
- endpoint_url=http://my_url:my_port
- endpoint_url="http://my_url:my_port"
- endpoint_url: http://my_url:my_port
- endpoint_url: "http://my_url:my_port"

I also made sure to erase my credentials file, closed/reopened VSCode and I still see nothing.  The one thing that changes is that I don't see the "Your Aws Access method is not credentials file" warning anymore.

Thanx for directions :-)

**Comment by necatiarslan** [comment]
I haven't seen the method settings.json you use for aws credentials before.
Please follow aws best practices. It is just put your credentials in a credentils file and config file under aws folder.

For more detail on aws credentials
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html
https://www.youtube.com/watch?v=SON8sY1iOBU

![Screen Shot 2023-12-07 at 09 58 47](https://github.com/necatiarslan/aws-s3/assets/1336688/8fdfd866-93d5-4b23-bf49-f7a6b05e3adc)

for end point, just use http://my_url:my_port format to specify the end point in the extension, not somewhere else.
![Screen Shot 2023-12-07 at 09 56 34](https://github.com/necatiarslan/aws-s3/assets/1336688/600d4773-5400-4bc3-aa37-5b47ed1ee17d)

**Comment by ymoisan** [comment]
With ~/.aws/credentials 

```
[default]
aws_access_key_id=my_access_key
aws_secret_access_key=my_secret_access_key
```

And inputting "http://my_url:my_port" as you mentioned above  : still nothing.

Are there any logs I could see ?

**Comment by necatiarslan** [comment]
I have added extended aws credentials support with the new version v1.7.1
Pls install and retry and let me know if it worked or not
