### ISSUE TITLE
Local S3 support

### ISSUE THREAD

**Issue by mhonnatti** [necatiarslan/aws-s3#4]
Hello! Great work with this! Do you have plans to allow local S3 ops? Would be great for local development! For e.g., we use LocalStack for mocking S3 (and other AWS services) locally as we develop. I suspect a relatively low lift solution could be to expose `--endpoint-url` as a configurable param?

**Comment by necatiarslan** [comment]
Sure, I can add a feature to provide your custom endpoint.
I added this feature to my to-do list.
I don't have localstack in my local machine to test it out.
Can you help me with this test?

**Comment by necatiarslan** [comment]
1. download https://github.com/necatiarslan/aws-s3/raw/main/vsix/aws-s3-vscode-extension-1.1.2.vsix and install
2. Run "Update Aws EndPoint" command and provide your localstack URL

Pls let me know if it worked or you had an error

**Comment by mhonnatti** [comment]
That worked just as expected!

**Comment by necatiarslan** [comment]
thanks
