### ISSUE TITLE
api.GetBucketList Error

### ISSUE THREAD

**Issue by srolel** [necatiarslan/aws-s3#5]
Hello! thanks for implementing this! I get this Error when trying to access a bucket:

```
api.GetBucketList Error !!! | CredentialsError | Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
```

I'm logged in using SSO and select the right profile.

**Comment by necatiarslan** [comment]
Hi, Unfortunately, the extension does not support SSO authentication. It supports only Credential File. 

For more detail on aws credentials
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html
https://www.youtube.com/watch?v=SON8sY1iOBU
