### ISSUE TITLE
light color theme support

### ISSUE THREAD

**Issue by dominikdeka** [necatiarslan/aws-s3#6]
Is there a chance to add support for light color theme? 

This is how it looks on my side in `Light (Visual Studio)` theme:

![Screenshot_20230322_135128](https://user-images.githubusercontent.com/11920529/226910580-50b8ddcf-be10-45f8-9262-d018f8b68899.png)

**Comment by dominikdeka** [comment]
voted,

btw, this project is really great job and helps me a lot at daily work!

**Comment by necatiarslan** [comment]
I have added full theme support with the new version v1.3

here are all new features
- File: rename, copy, move
- Full Theme support
- Add bucket: do not search if bucket name entered (thanks Ferabeo #12)
- Copy shortcut key
- Add shortcut with key
- Goto File/Folder
- Hide Bucket/Shortcuts
- Environment Varible Credentials Support
