### ISSUE TITLE
multiple AWS config profiles

### ISSUE THREAD

**Issue by mariuszATontario** [necatiarslan/aws-s3#7]
I have multiple profiles defined in my .aws\config file. How do I switch between the profiles? It would seem that AWS-S3 always selects default profile. thx.

-M

**Comment by necatiarslan** [comment]
You can click the person icon at the top to switch between accounts.
The third icon is at the top right.

![image](https://user-images.githubusercontent.com/1336688/236817352-ba6ecf9b-fd6a-4d7d-8b3f-7b68bdc556e0.png)
