### ISSUE TITLE
How to use custom endpoint-url with extension in ssh-remote session?

### ISSUE THREAD

**Issue by kenjim** [necatiarslan/aws-s3#8]
I'm trying to use your aws-s3 extension where I need to specify the --endpoint-url in all aws CLI calls.  I'm using aws cli v1 on the remote ssh server.  Your help is appreciated.

**Comment by necatiarslan** [comment]
To update the enpoint url, click the 3 dots button (the last button on the treeview in the left panel), then you will see the update menu item.
let me know if it works

**Comment by kenjim** [comment]
Unfortunately, I still couldn't get it to work.  My .aws/config is as follows, and I have export AWS_SDK_LOAD_CONFIG=1 in my .bashrc.  The endpoint looks like http://hostname.domain.net:80 which points to an internal filer endpoint.

[profile foo-bar]
aws_access_key_id=KEY
aws_secret_access_key=KEY

[profile bar-foo]
aws_access_key_id=KEY
aws_secret_access_key=KEY

**Comment by kenjim** [comment]
I press + button to add the bucket name, but I get following error:

api.GetBucketList Error !!! | CredentialsError | Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1

**Comment by necatiarslan** [comment]
pls try again with the new version 1.3

**Comment by necatiarslan** [comment]
I have added extended aws credentials support with the new version v1.7.1
Pls install and retry and let me know if it worked or not
